version: '3.8'
services:
  sql-server:
    container_name: shop-database
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Initial123!
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE
    volumes:
      - sql-server-volume:/var/opt/mssql
  api:
    container_name: shop-api
    build:
      context: .
      dockerfile: Dockerfile
    image: shop-api
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_URLS=https://+:3000;http://+:3001
      - ConnectionStrings:Sql=server=sql-server,1433;User Id=SA;Password=Initial123!;
      - ASPNETCORE_ENVIRONMENT=<environment>
      - Azure:ServiceBus:ConnectionString=<azure_service_bus_connection_string>
      - Azure:ServiceBus:QueueOrTopicName=<azure_service_bus_queue_or_topic>
    ports:
      - "3000:3000"
      - "3001:3001"
volumes: 
  sql-server-volume:
    driver: local